blank_issues_enabled: true
contact_links:
  - name: Suggest a feature
    url: https://winappsdk.productboard.com/portal/1-windows-app-sdk/tabs/60f2ef79-bbf3-43de-a659-31039e50c9ec
    about: Suggest a new feature or idea, or vote on existing ideas
  - name: Question
    url: https://github.com/microsoft/WindowsAppSDK/discussions/new?category=q-a
    about: Ask a question
  - name: Discussion
    url: https://github.com/microsoft/WindowsAppSDK/discussions/new?category=general
    about: Start a discussion