name: Feature proposal
description: Suggest a new feature or idea
title: 'Proposal:'
labels: feature proposal
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: Include 1-2 sentences summarizing your feature or API proposal.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Rationale
      description: Create a list that describes WHY the feature should be added to Windows App SDK for all developers and users. Proposals often have multiple motives for why we should do the work, so list each one as a separate bullet.
  - type: textarea
    attributes:
      label: Important notes
      description: Please include any other important details.
